export default config = {
    MIDI_INSTRUMENT_PLAYER_RIGHT: "KOMPLETE KONTROL M32",
    MIDI_INSTRUMENT_PLAYER_LEFT: "Launchkey MK3 49 LKMK3 MIDI Out",
    SOCKET_PORT: 8080,

    ESP_MODE: false,
    DEMO_MODE: false,
}